apiVersion: v1
kind: ConfigMap
metadata:
  name: food-app-config
  namespace: monitoring
data:
  application.yaml: |
    spring:
      application:
        name: food-app-backend

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus

      endpoint:
        health:
          show-details: always
          probes:
            enabled: true

      metrics:
        export:
          prometheus:
            enabled: true
            step: 1m