apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
  namespace: monitoring
  labels:
    app: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app
          # Bu qator juda muhim! CI/CD (GitHub Actions) versiyani shu yerga yozadi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          # Dastur "tirikmi" tekshirish uchun
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          # Dastur "ishlashga tayyormi" tekshirish uchun
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi