{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: food-app
  namespace: monitoring
  labels:
    app: food-app
    release: prometheus  # Bu label Prometheus topishi uchun kerak
spec:
  selector:
    matchLabels:
      app: food-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
{{- end }}